var categoryList = [
  'Finance',
  'IT',
  'Operations',
  'Information',
  'Sales',
  'Marketing',
  'Corporate',
  'Department',
  'Regional',
  'Music',
  'Visual Arts',
  'Performing Arts',
  'Film',
  'Lectures & Books',
  'Fashion',
  'Food & Drink',
  'Festivals & Fairs',
  'Charities',
  'Sports & Active Life',
  'Nightlife',
  'Kids & Family',
];
